USE DATABASE HEALTHCARE_DB;
USE SCHEMA PUBLIC;
SHOW TABLES;
SELECT
    p.PATIENT_NAME,
    d.DOCTOR_NAME,
    d.SPECIALIZATION,
    a.CONSULTATION_FEE,
    a.DIAGNOSIS
FROM APPOINTMENT a
JOIN PATIENT p
ON a.PATIENT_ID = p.PATIENT_ID
JOIN DOCTOR d
ON a.DOCTOR_ID = d.DOCTOR_ID
LIMIT 400;
SELECT
    SUM(AMOUNT) AS TOTAL_REVENUE
FROM BILLING;
SELECT
d.DOCTOR_NAME,
COUNT(a.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM DOCTOR d
JOIN APPOINTMENT a
ON d.DOCTOR_ID = a.DOCTOR_ID
GROUP BY d.DOCTOR_NAME
ORDER BY TOTAL_APPOINTMENTS DESC;
SELECT
CITY,
COUNT(*) AS TOTAL_PATIENTS
FROM PATIENT
GROUP BY CITY;
SELECT *
FROM APPOINTMENT
ORDER BY CONSULTATION_FEE DESC
LIMIT 10;
CREATE OR REPLACE VIEW DOCTOR_PERFORMANCE_VIEW AS
SELECT
    d.DOCTOR_NAME,
    d.SPECIALIZATION,
    COUNT(a.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM DOCTOR d
JOIN APPOINTMENT a
ON d.DOCTOR_ID = a.DOCTOR_ID
GROUP BY d.DOCTOR_NAME, d.SPECIALIZATION;
SELECT * FROM DOCTOR_PERFORMANCE_VIEW;
CREATE OR REPLACE VIEW HOSPITAL_REVENUE_MV AS
SELECT
STATUS,
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM BILLING
GROUP BY STATUS;
SELECT * FROM HOSPITAL_REVENUE_MV;
CREATE OR REPLACE STREAM PATIENT_STREAM
ON TABLE PATIENT;
SHOW STREAMS;
CREATE OR REPLACE TASK BILLING_TASK
WAREHOUSE = HEALTHCARE_WH
SCHEDULE = '5 MINUTE'
AS
INSERT INTO BILLING
SELECT * FROM BILLING
WHERE AMOUNT > 10000;
ALTER TASK BILLING_TASK RESUME;
CREATE OR REPLACE DYNAMIC TABLE PATIENT_SUMMARY
TARGET_LAG = '5 minutes'
WAREHOUSE = HEALTHCARE_WH
AS
SELECT
CITY,
COUNT(*) AS TOTAL_PATIENTS
FROM PATIENT
GROUP BY CITY;
SELECT * FROM PATIENT_SUMMARY;
SELECT
VARIANT_COL:recordId::INT AS RECORD_ID,
VARIANT_COL:patientId::INT AS PATIENT_ID,
VARIANT_COL:prescriptionJson.medicine::STRING AS MEDICINE,
VARIANT_COL:prescriptionJson.dosage::STRING AS DOSAGE,
VARIANT_COL:labReportJson.bp::STRING AS BLOOD_PRESSURE,
VARIANT_COL:labReportJson.sugar::INT AS SUGAR_LEVEL
FROM MEDICAL_RECORD;
